-- 标记因降级而被禁用的应用和卡密，便于升级时精确恢复
ALTER TABLE apps  ADD COLUMN IF NOT EXISTS downgraded BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS downgraded BOOLEAN NOT NULL DEFAULT FALSE;

